version: "3.9"
services:
   frontend:
    container_name: NG.CASH-FrondEnd
    build: ./web
    ports:
      - 3000:3000
    working_dir: /app/web
    volumes:
      - ./web:/app/web
    tty: true
    stdin_open: true
    # command: bash
    restart: always
    depends_on:
      - backend
    networks:
      - virtual_wan_Front-to-Back  

   backend:
    container_name: backend-api
    build: ./server
    working_dir: /app/server
    volumes:
      - ./server:/app/server
    stdin_open: true
    tty: true
    restart: always 
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: postgres
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ngcash_db?schema=public
      JWT_SECRET: secretJWT 
    networks:
      - virtual_wan_Front-to-Back
      - virtual_lan_Back-to-DB  
 
   postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ngcash_db 
     
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - virtual_lan_Back-to-DB
      - postgres
    cap_add:
      - SYS_NICE  

   pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"   
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped  
networks:
  virtual_wan_Front-to-Back: {}
  virtual_lan_Back-to-DB: {}
  postgres:
   driver: bridge
volumes:
    postgres-data:
    pgadmin-data:   

